version: '2.1'
orbs:
  mabl-trigger-tests: mabl/trigger-tests@1.0.4
jobs:
  mabl:
    machine: true
    steps:
      - mabl-trigger-tests/run-tests:
          api-key: MABL_API_KEY
          application-id: eHL81RPSjuVW4fUcxoDtbw-a
          environment-id: Jw7oBZlxKXVGxK3_eWxcWQ-e
          url: http://www.ietf.org/         
workflows:
  run-tests:
    jobs:
      - mabl

