version: '2.1'
orbs:
  mabl-trigger-tests: mabl/trigger-tests@1.0.6
jobs:
  mabl:
    machine: true
    steps:
      - mabl-trigger-tests/run-tests:
          api-key: MABL_API_KEY
          application-id: pqemGZA1wQIFRKaGb4IUzg-a
          environment-id: Jw7oBZlxKXVGxK3_eWxcWQ-e
      - mabl-trigger-tests/parse-results
workflows:
  run-tests:
    jobs:
      - mabl

